name: vqvae_base # 256px images
quantizer_type: single   # or single
vocab_size: 4096
z_channels: 32
ch: 128
ch_mult: [1, 1, 2, 2, 4]
num_res_blocks: 2
dropout: 0.0
beta: 0.25
using_znorm: false
quant_conv_ks: 3
patch_nums: [1, 2, 4, 8, 16]
