name: var_base
vocab_size: 4096
dim: 512
depth: 8
num_heads: 8
mlp_ratio: 4.0
dropout: 0.0
drop_path_rate: 0.0333
attn_l2_norm: true
init_head: 0.02
init_std: -1.0
init_adaln: 0.5
init_adaln_gamma: 1.0e-5
num_classes: 1000
cond_drop_rate: 0.1   # probability of replacing class label with unconditional token during training
label_smoothing: 0.0
