defaults:
  - datasets: imagenet
  - tokenizer: vqvae_base
  - _self_

seed: 42
device: cuda:1

amp: true   # enable mixed precision (autocast)
recon_loss_type: mse
batch_size: 32
num_workers: 8
pin_memory: true
num_save_images: 16

output_root: experiments/tokenizer

hydra:
  run:
    dir: ${output_root}/${now:%Y-%m-%d_%H-%M-%S}
