defaults:
  - var: var_base
  - tokenizer: vqvae_base
  - _self_

seed: 42
device: cuda:1

var_checkpoint_path: /data/ahmed.ghorbel/projects/10-var/checkpoints/var/2026-04-14_18-34-32/last.pt
tokenizer_checkpoint_path: /data/ahmed.ghorbel/projects/10-var/checkpoints/tokenizer/vae_ch160v4096z32.pth

use_ema: true  # load EMA weights from checkpoint if available

num_samples: 16
batch_size: 8

temperature: 0.9
top_k: 200
top_p: 0.9
start_token: null
sample_prefix: sample

output_dir: experiments/var

hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
