defaults:
  - datasets: imagenet
  - tokenizer: vqvae_base
  - _self_

seed: 42
device: cuda:1

checkpoint_path: checkpoints/tokenizer/vae_ch160v4096z32.pth
splits: [train, val]
batch_size: 32
num_workers: 8
pin_memory: true
output_root: /data/tii/data/imagenet1k_256px/tokens

hydra:
  run:
    dir: ${output_root}/${now:%Y-%m-%d_%H-%M-%S}
